### ISSUE TITLE
Initial Upgrade error

### ISSUE THREAD

**Issue by Denford29** [Adolfi/UmbracoNineDemoSite#5]
Cloned the code to have a play and on the initial run, the umbraco upgrade screen came up trying to upgrade the sdf database so converted it to a local sql database and then had another database error 

`The database failed to upgrade. ERROR: The database configuration failed with the following message: 'FK_umbracoRedirectUrl_umbracoNode_uniqueID' is not a constraint`

So had to "hack" in the constraint with this script

`ALTER TABLE umbracoRedirectUrl
ADD CONSTRAINT FK_umbracoRedirectUrl_umbracoNode_uniqueID CHECK (Id != null);`

So the upgrade can proceed and remove it :), just putting this here more for an fyl i guess as i have got past it,

Actual log in the log file is below:

`{"@t":"2021-08-03T11:29:07.7897593Z","@mt":"Database configuration failed","@l":"Error","@x":"System.Data.SqlServerCe.SqlCeException (0x80004005): Cannot alter column of type NTEXT or IMAGE [ Column Name = data ]\r\n   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)\r\n   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)\r\n   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)\r\n   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 281\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)\r\n   at NPoco.Database.Execute(Sql Sql)\r\n   at NPoco.Database.Execute(String sql, Object[] args)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.ExecuteStatement(StringBuilder stmtBuilder)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.Execute()\r\n   at Umbraco.Cms.Infrastructure.Migrations.Expressions.Execute.ExecuteBuilder.Do()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.AlterColumn[T](String tableName, String columnName)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_8_15_0.AddCmsContentNuByteColumn.Migrate()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, IScopeProvider scopeProvider, IKeyValueService keyValueService)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(UmbracoPlan plan)","SourceContext":"Umbraco.Cms.Infrastructure.Migrations.Install.DatabaseBuilder","ActionId":"6a7b1838-f82a-4938-8640-ccbb6fdcabf7","ActionName":"Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall (Umbraco.Web.BackOffice)","RequestId":"80000008-0004-f300-b63f-84710c7967bb","RequestPath":"/install/api/PostPerformInstall","ProcessId":3408,"ProcessName":"iisexpress","ThreadId":18,"AppDomainId":1,"AppDomainAppId":"52972cfa0511fad25ec89b50a95b9e35bc00e389","MachineName":"DESKTOP-Q638HB1","Log4NetLevel":"ERROR","HttpRequestId":"fe93197b-71a7-4d99-adb0-1c2852ef6d83","HttpRequestNumber":6,"HttpSessionId":"e603b8a9-873c-08da-218a-f33e411f46aa"}

{"@t":"2021-08-03T12:27:48.0412468Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): 'FK_umbracoRedirectUrl_umbracoNode_uniqueID' is not a constraint.\r\nCould not drop constraint. See previous errors.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 281\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)\r\n   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)\r\n   at NPoco.Database.Execute(Sql Sql)\r\n   at NPoco.Database.Execute(String sql, Object[] args)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.ExecuteStatement(StringBuilder stmtBuilder)\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationExpressionBase.Execute()\r\n   at Umbraco.Cms.Infrastructure.Migrations.Expressions.Common.ExecutableBuilder.Do()\r\n   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_8_15_0.UpgradedIncludeIndexes.Migrate()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()\r\n   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, IScopeProvider scopeProvider, IKeyValueService keyValueService)\r\n   at Umbraco.Cms.Infrastructure.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(UmbracoPlan plan)\r\nClientConnectionId:31e1e3d2-447f-45cf-bc25-83ce81710926\r\nError Number:3728,State:1,Class:16","InstanceId":"733a7681","SourceContext":"Umbraco.Cms.Infrastructure.Persistence.UmbracoDatabase","ActionId":"6d8ce72f-c9fb-4bfb-a290-b6c4916c28e6","ActionName":"Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall (Umbraco.Web.BackOffice)","RequestId":"80000008-000a-fc00-b63f-84710c7967bb","RequestPath":"/install/api/PostPerformInstall","ProcessId":21608,"ProcessName":"iisexpress","ThreadId":105,"AppDomainId":1,"AppDomainAppId":"52972cfa0511fad25ec89b50a95b9e35bc00e389","MachineName":"DESKTOP-Q638HB1","Log4NetLevel":"ERROR","HttpRequestId":"9513c34a-4d2f-4a6a-a1dc-9d275a6cd19b","HttpRequestNumber":6,"HttpSessionId":"81213d84-4d7c-1b77-fa2a-54eae8677338"}
`

**Comment by Adolfi** [comment]
That's really strange that you got the upgrade screen but thanks for sharing your findings.
#h5yr
