### ISSUE TITLE
Testing v.9.0.0-beta004 demo - first-run upgrade error

### ISSUE THREAD

**Issue by dmueller-sa** [Adolfi/UmbracoNineDemoSite#7]
After cloning and running demo project, an upgrade required notice displays:
https://www.screencast.com/t/QvjPBe7SuHj

After clicking the continue button the following error displays:
https://www.screencast.com/t/aLVKRsZiakQ

Please advise. Thanks!

**Comment by Denford29** [comment]
i had the same error before and thought it was just my cloned solution see, https://github.com/Adolfi/UmbracoNineDemoSite/issues/5 , i ended up pretty much having to actually create a sql server db to use instead.

**Comment by Adolfi** [comment]
It's strange that this only happens to some.
Literally yesterday I wiped my entire setup and cloned the project (with db) in to a clean folder and it worked right of the bat.

According to your screendump, Umbraco is trying to install 9.0.0-rc001, I will try and upgrade the project locally and see if I get any errors and if not I can push a new version. 

Hold tight.. :)

**Comment by Adolfi** [comment]
Ok so I found this really strange version conflict but it is solved now. All project are now updated to the latest RC003 version.
Please try and wipe your local project and clone fresh and see if it works for you.
Best of luck!

**Comment by Denford29** [comment]
Cheers will do and re-clone and let you know how i get on, want to even further experiment and see if i can run it in a Docker container :)

**Comment by dmueller-sa** [comment]
Thank you. It is working now after cloning latest. I appreciate your assistance with this issue and I'm looking forward to seeing more of Umbraco 9!
