### ISSUE TITLE
Replace ContentAtXPath

### ISSUE THREAD

**Issue by bjarnef** [Adolfi/UmbracoNineDemoSite#9]
I noticed `ContentAtXPath()` is used here: 
https://github.com/Adolfi/UmbracoNineDemoSite/blob/master/UmbracoNineDemoSite.Core/Features/Shared/Settings/SiteSettings.cs#L17-L18

In both Umbraco v8 and v9 there is no longer an XML config/cache, so it is NuCache representation as XML and using XPathNavigator. Most of the time we don't need it though.

So with NuCache it should be faster using the LINQ queries or in other cases Examine.

Something like this:

```
private IPublishedContent home => this.umbracoHelper.ContentAtRoot().Where(x => x.ContentType.Alias == ContentTypeAlias.Home)?.FirstOrDefault();
private IPublishedContent settings => this.umbracoHelper.ContentAtRoot().Where(x => x.ContentType.Alias == ContentTypeAlias.SiteSettings)?.FirstOrDefault();
```
or

```
private IPublishedContent home => this.umbracoHelper.ContentAtRoot().FirstOrDefault(x => x.ContentType.Alias == ContentTypeAlias.Home);
private IPublishedContent settings => this.umbracoHelper.ContentAtRoot().FirstOrDefault(x => x.ContentType.Alias == ContentTypeAlias.SiteSettings);
```

Furthermore I think it could use `.Value()` / `Value<T>()`  extension method if the code should be a bit more simpler.

```
public string CallToActionHeader => this.settings.Value<string>(PropertyAlias.CallToActionHeader);
```

**Comment by Adolfi** [comment]
Hi @bjarnef!
Thanks. Related to a recent discussion/question on twitter: https://twitter.com/YodasMyDad/status/1441669868487512072
I think just boils down to old habit. It would definetly be better in a demo site to avoid XPath and instead use your suggested approach. Would you be up for contributing?

Regarding the .Value<T> extensions: Yes I am aware that this looks better, however this is not unit testable. At least not at the time when I was building this project in the first beta. So its an active decition. This might have changed now, and you are welcome to change all .Value() to .Value<T> in your PR, as long as its still testable.

Thanks for being involved!
Cheers! ❤️

**Comment by mistyn8** [comment]
I think some of this comes from 
https://our.umbraco.com/documentation/Reference/Common-Pitfalls/index-v7#too-much-linq---xpath-is-still-your-friend ??
was still the v8 documentation
(Though MNTP XPath is still a must for me!)

https://umbracospark.com/media/p0xgaq2u/querying-umbraco.pptx should be required reading :-) 

![image](https://user-images.githubusercontent.com/12418214/135255437-cec5c864-9fde-4937-936b-024b7a96a825.png)

**Comment by bjarnef** [comment]
@Adolfi yeah, in this case it could just use LINQ querying. I'll see if I find some time to update and submit a PR if you or others hasn't already fixed it at that time 😁 

I thought it had something to to with the unit testing. Not sure if there's a specific reason the extension methods aren't testable or if it could be with some changes 😎
